version: "3"
services:
  api:
    build: ./
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 3001:3000
  db:
    image: postgres
    volumes:
      - db_store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  db_store:
